### ISSUE TITLE
Remove share button from RSS feed?

### ISSUE THREAD

**Issue by JanRei** [ciubotaru/share-on-diaspora#58]
The plugin adds the share button also into the RSS feed. However, the feed readers I am using either do not show the button (because the post is shortened) or the share button is shown as unclickable text. Maybe it would make sense to remove the button from the feed?

**Comment by ciubotaru** [comment]
Yes, you are right. Now I have to find out how to do it (currently, the button image and code are simply appended to the post contents)...

**Comment by JanRei** [comment]
One way could be to add a check in diaspora_button_display() using is_feed() function provided by WordPress. It returns true if a feed is being generated. So something like this should work:

    if ( !is_feed() && get_post_type() == 'post' && ( ! in_array( 'get_the_excerpt', $GLOBALS['wp_current_filter'] )) ) {

**Comment by ciubotaru** [comment]
First of all, let me confirm the behavior that you reported. Indeed, if the feed is set to "Full Text" (in Reading Settings of the admin panel), then feed readers display non-clickable text and image at the end of the post. So, yes, it's a bug and should be tagged as such. Also, just as you said, certain readers shorten the post and do not display the ending.

Second, the code you propose will definitely work. However, instead of fixing the non-functional button, it simply removes the text and image. I am not sure if this is the best approach.

I assume that plugin users (i.e. blog admins/authors) want a working button (otherwise, why would they install the plugin?). I think that plugin users should be able to choose whether they want the button in the feed or not. So my plan is:

* investigate why the button does not work
* make it work
* add a setting to enable/disable the button in feeds (this last point will include the code you posted above).

**Comment by ciubotaru** [comment]
Update:
* the button does not work because the link is a javascript function, and javascript does not work is rss feeds.
* the button can be fixed by removing javascript (this strips some functionality like setting the size of pod selection window)

Please, have a look at https://github.com/ciubotaru/share-on-diaspora/commit/fcaaded8a56ff993a803bd39920ca3843b7bd3ff for a tentative fix.

**Comment by JanRei** [comment]
I just thought removing the button would be the simplest approach, but your plan sounds good.

The button indeed seems to work now in most feed readers I have tested. Maybe some small improvements to the styling would be nice.

**Comment by ciubotaru** [comment]
Update:

* A checkbox to enable/disable the button in rss feeds was added (see https://github.com/ciubotaru/share-on-diaspora/commit/9f6950386485303fbe25ef99986267fa06295da9). Too many settings for such a minor plugin?

> Maybe some small improvements to the styling would be nice.

If you have any ideas, please share. I'm a no good designer.

**Comment by JanRei** [comment]
I installed the plugin from issue58 branch. The new option to show the share button in feeds is enabled by default in admin menu. However, the button does not appear in my feed. Instead, I get the following notice:

> Notice:  Undefined index: show_in_feeds in wordpress\wp-content\plugins\share-on-diaspora-issue58\class.php on line 143

When I disable the option in admin menu I see the following notice:

> Notice:  Undefined index: show_in_feeds in wordpress\wp-content\plugins\share-on-diaspora-issue58\admin.php on line 396

**Comment by ciubotaru** [comment]
I addressed the two notices in https://github.com/ciubotaru/share-on-diaspora/commit/32246205e1108e95289e66a4cbc893f85de3c0c9 and in https://github.com/ciubotaru/share-on-diaspora/commit/d2048fcb5d4a484727caab5b2e2b0af3a9726211. Could you, please, check if the feeds are displaying properly now?

**Comment by JanRei** [comment]
After installing the plugin I get now the following notice on miscellaneous settings page:

> Notice:  Undefined index: show_in_feeds in wordpress\wp-content\plugins\share-on-diaspora-issue58\admin.php on line 322

And there is a warning and a notice on button options page:
> Warning:  Missing argument 3 for ShareOnDiaspora::generate_button(), called in wordpress\wp-content\plugins\share-on-diaspora-issue58\admin.php on line 416 and defined in wordpress\wp-content\plugins\share-on-diaspora-issue58\class.php on line 96

> Notice:  Undefined variable: is_feed in wordpress\wp-content\plugins\share-on-diaspora-issue58\class.php on line 134

**Comment by ciubotaru** [comment]
> After installing the plugin I get now the following notice on miscellaneous settings page:
>>   Notice: Undefined index: show_in_feeds in wordpress\wp-content\plugins\share-on-diaspora-issue58\admin.php on line 322

Ah, yes, I broke it again in the following commit. Should be OK now.

> And there is a warning and a notice on button options page:
>> Warning: Missing argument 3 for ShareOnDiaspora::generate_button(), called in wordpress\wp-content\plugins\share-on-diaspora-issue58\admin.php on line 416 and defined in wordpress\wp-content\plugins\share-on-diaspora-issue58\class.php on line 96
>> Notice: Undefined variable: is_feed in wordpress\wp-content\plugins\share-on-diaspora-issue58\class.php on line 134

I fixed it on my test system, but forgot to push to repository. Should be OK now.

Thank you for your report and sorry for inconvenience.

**Comment by JanRei** [comment]
I do not get any warnings or notices anymore. So I think the issue can be closed.

**Comment by ciubotaru** [comment]
Great. I merged the changes into 'unstable' and, if no other changes are proposed (button styling maybe), I will be merge it into 'master' and release. It's time for 0.7, I guess.

**Comment by JanRei** [comment]
I have no other suggestions at the moment. If needed I can translate the new strings into German.

**Comment by ciubotaru** [comment]
> If needed I can translate the new strings into German.

That would be great! I updated all files needed for translation in 'unstable' branch (for offline translation), and also updated strings at [PoEditor.com](https://poeditor.com/projects/view?id=10673) (for online translation).

**Comment by JanRei** [comment]
I updated the translation on poeditor.com.
